export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_COMPANY = 'GET_COMPANY';
export const COMPANY_LOADING = 'COMPANY_LOADING';
export const COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND';
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRENT_COMPANY';
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_FULFILLER = 'GET_FULFILLER';
export const FULFILLER_LOADING = 'GET_COMPANIES';
export const FULFILLER_NOT_FOUND = 'FULFILLER_NOT_FOUND';
export const CLEAR_CURRENT_FULFILLER = 'CLEAR_CURRENT_FULFILLER';
export const GET_FULFILLERS = 'GET_COMPANIES';



